[[plugin]]
id = "peruzzoarthur/nix-logo"
name = "Nixos Logo"
version = "1.0.1"
author = "peruzzoarthur"
license = "MIT"
plugin_api = 3
icon = "image"
description = "Nixos logo for styling the bar"
min_noctalia = "5.0.0"
tags = ["nixos"]


[[plugin]]
id = "peruzzoarthur/hyprwhspr"
name = "Hyprwhspr"
version = "1.0.0"
author = "peruzzoarthur"
license = "MIT"
plugin_api = 3
icon = "microphone"
description = "Bar indicator for hyprwhspr-rs voice dictation."
tags = ["dictation", "voice", "hyprland"]
dependencies = ["hyprwhspr-rs"]
