[[plugin]]
id = "peruzzoarthur/nixos-logo"
name = "Nixos Logo"
version = "1.0.0"
author = "peruzzoarthur"
license = "MIT"
icon = "image"
description = "Nixos logo for styling the bar"
min_noctalia = "5.0.0"
tags = ["nixos"]

